#ifndef EMM_INDEX_H_
#define EMM_INDEX_H_

#define UARHO1  0
#define UARHO2  1
#define UARHO3  2
#define UMX     3
#define UMY     4
#define UMZ     5
#define URHOE   6
#define UARP    7
#define NCONS   8
#define GV11    8
#define GV21    9
#define GV31    10
#define GV12    11
#define GV22    12
#define GV32    13
#define GV13    14
#define GV23    15
#define GV33    16
#define GALPHA1 17
#define GALPHA2 18
#define NV      19
#define GPRESS  19
#define GT1     20
#define GT2     21
#define GT3     22
#define NV2     23

#define QALPHA1 0
#define QALPHA2 1
#define QRHO1   2
#define QRHO2   3
#define QRHO3   4
#define QU      5
#define QV      6
#define QW      7
#define QPRES   8
#define QPI     9
#define QV11    10
#define QV21    11
#define QV31    12
#define QV12    13
#define QV22    14
#define QV32    15
#define QV13    16
#define QV23    17
#define QV33    18
#define NPRIM   19

#define ORHO   0
#define OE     1
#define OSOS   2
#endif